# Generated by Django 4.2 on 2023-04-22 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=60, verbose_name='User name')),
                ('user_password', models.CharField(max_length=16, verbose_name='User password')),
            ],
        ),
    ]
